name: Build .NET Desktop App

on:
  release:
    types:
      - created


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            platform: Windows
          - os: ubuntu-latest
            platform: Linux
          - os: macos-latest
            platform: macOS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Get version from .csproj and append build number
      id: get_version
      shell: pwsh
      run: |
        $csprojPath = Join-Path -Path "EndlessRealms.GUI" -ChildPath "EndlessRealms.Gui.csproj" # Update this line to match the actual folder and file names
        $xmlContent = [xml](Get-Content -Path $csprojPath)
        $version = $xmlContent.Project.PropertyGroup.Version
        $versionWithBuildNumber = "$version.${env:GITHUB_RUN_NUMBER}"
        echo "Version with build number is $versionWithBuildNumber"
        echo "::set-output name=version_with_build_number::$versionWithBuildNumber"


    - name: Build and publish
      run: dotnet publish EndlessRealms.GUI/EndlessRealms.Gui.csproj -c Release -o publish --no-self-contained --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || 'osx-x64' }}

    - name: Zip publish folder
      shell: pwsh
      run: |
        $zipFileName = "EndlessRealms.${{ steps.get_version.outputs.version_with_build_number }}.${{ matrix.platform }}.zip"
        if ($env:RUNNER_OS -eq "Windows") {
          Compress-Archive -Path publish\* -DestinationPath $zipFileName
        } else {
          zip -r $zipFileName publish/
        }
        echo "ZipFileName=$zipFileName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append


    - name: Upload artifact as release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.ZipFileName }}
        asset_name: ${{ env.ZipFileName }}
        asset_content_type: application/zip
