name: Build .NET Desktop App

on:
  release:
    types:
      - created


jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-arm64-latest]
        include:
          - os: windows-latest
            runs-on: windows-latest
            platform: Windows
          - os: ubuntu-latest
            runs-on: ubuntu-latest
            platform: Linux
          - os: macos-latest
            runs-on: macos-latest
            platform: macOS
          - os: macos-arm64-latest
            runs-on: macos-latest
            platform: macOS-arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Build and publish Web
      run: dotnet publish EndlessRealms.WebUi/EndlessRealms.WebUi.csproj -c Release -o publish_web --self-contained --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || matrix.os == 'macos-latest' && 'osx-x64' || matrix.os == 'macos-arm64-latest' && 'osx-arm64' }}


    - name: Zip publish folder GUI
      shell: pwsh
      run: |
        $zipFileName = "EndlessRealms.webui.${{ github.event.release.tag_name }}.${{ matrix.platform }}.zip"
        if ($env:RUNNER_OS -eq "Windows") {
          Compress-Archive -Path publish_web\* -DestinationPath $zipFileName
        } else {
          zip -r $zipFileName publish_web/
        }
        echo "WebZipFileName=$zipFileName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append


    - name: Upload artifact as release asset GUI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.WebZipFileName }}
        asset_name: ${{ env.WebZipFileName }}
        asset_content_type: application/zip        
